#!/bin/bash
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y autoremove

#SSH
sudo apt install openssh-server -y

#google-crome
# 1. 必要なツールをインストール
sudo apt update
sudo apt install -y wget gnupg

# 2. Googleの署名鍵を取得して登録
wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-linux-signing-key.gpg

# 3. Chromeのリポジトリを追加
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list

# 4. パッケージリストを更新
sudo apt update

# 5. Google Chromeをインストール（Stable版）
sudo apt install -y google-chrome-stable

#python-library
sudo apt install pip -y
sudo pip install selenium --break-system-packages
sudo pip install mysql-connector-python --break-system-packages
sudo pip install pandas --break-system-packages

#crontab
crontab /home/aweqse/keiba/crontab/keiba_crontab

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y autoremove 

