#!/bin/bash
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y autoremove

#vscode
sudo apt install /home/aweqse/keiba/deb/code_1.96.0-1733888194_amd64.deb

#SSH
sudo apt install openssh-server -y

#mysql
sudo apt install mysql-server-8.0 -f -y

#mysql-workbench
sudo snap install mysql-workbench-community 

#google-crome
sudo apt install /home/aweqse/keiba/deb/google-chrome-stable_current_amd64.deb

#python-library
sudo apt install pip -y
sudo pip install selenium --break-system-packages
sudo pip install mysql-connector-python --break-system-packages
sudo pip install openpyxl --break-system-packages
sudo pip install pandas --break-system-packages
sudo pip install madplotlib --break-system-packages

#office
sudo apt install libreoffice -y

#crontab
crontab /home/aweqse/keiba/crontab/keiba_crontab

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y autoremove 

